export const EVENTS = {
	CONNECTED: 'CONNECTED',
	CURRENT_USER_UPDATE: 'CURRENT_USER_UPDATE',

	PRIVATE_CALL_START: 'PRIVATE_CALL_START',
	PRIVATE_CALL_END: 'PRIVATE_CALL_END',

	MESSAGE_SEND: 'MESSAGE_SEND',
	MESSAGE_UPDATE: 'MESSAGE_UPDATE',
	MESSAGE_DELETE: 'MESSAGE_DELETE'
} as const;

export type EVENTS = (typeof EVENTS)[keyof typeof EVENTS];
