export const EVENTS = {
	PING: 'PING',
	PONG: 'PONG',

	CONNECTED: 'CONNECTED',
	CURRENT_USER_UPDATE: 'CURRENT_USER_UPDATE',

	PRIVATE_CALL_INIT: 'PRIVATE_CALL_INIT',
	PRIVATE_CALL_RECEIVE: 'PRIVATE_CALL_RECEIVE',
	PRIVATE_CALL_ACCEPT: 'PRIVATE_CALL_ACCEPT',
	PRIVATE_CALL_ACCEPTED: 'PRIVATE_CALL_ACCEPTED',
	PRIVATE_CALL_REJECT: 'PRIVATE_CALL_REJECT',
	PRIVATE_CALL_REJECTED: 'PRIVATE_CALL_REJECTED',
	PRIVATE_CALL_START: 'PRIVATE_CALL_START',
	PRIVATE_CALL_JOIN: 'PRIVATE_CALL_JOIN',
	PRIVATE_CALL_END: 'PRIVATE_CALL_END',
	PRIVATE_CALL_ENDED: 'PRIVATE_CALL_ENDED',
	PRIVATE_CALL_ERROR: 'PRIVATE_CALL_ERROR',

	FRIEND_REQUEST_RECEIVED: 'FRIEND_REQUEST_RECEIVED',
	FRIEND_REQUEST_ACCEPTED: 'FRIEND_REQUEST_ACCEPTED',
	FRIEND_REQUEST_REJECTED: 'FRIEND_REQUEST_REJECTED',
	FRIEND_DELETE: 'FRIEND_DELETE',

	MESSAGE_SEND: 'MESSAGE_SEND',
	MESSAGE_UPDATE: 'MESSAGE_UPDATE',
	MESSAGE_DELETE: 'MESSAGE_DELETE'
} as const;

export type EVENTS = (typeof EVENTS)[keyof typeof EVENTS];
